### PR TITLE
Fix Tooltip positions by changing strategy to 'fixed'

### LINKED ISSUE #3966: Tooltip Positionierung mit fixed
Damit die Positionierung des Tooltips nicht durch Elemente mit `position: relative` beeinflusst wird, sollte `position: fixed` verwendet werden.

### PR DESCRIPTION
**Pull request by sdvg**

### CODE REVIEW

File: packages/components/src/utils/align-floating-elements.ts [hunk 1]
```diff
@@ -18,6 +18,7 @@ export const alignFloatingElements = async ({ floatingElement, referenceElement,
 		const { x, y, middlewareData, placement } = await computePosition(referenceElement, floatingElement, {
 			placement: align,
 			middleware: middleware,
+			strategy: 'fixed',
```
Comment (deleonio) [inline packages/components/src/utils/align-floating-elements.ts:21]: 👍

**Review by deleonio — APPROVED** [review]

**Review by laske185 — APPROVED** [review]
