### PR TITLE
Fix: KolSelect getValue returns undefined initially

### LINKED ISSUE #6440: 🐞 Bug: KolSelect: `getValue` resolved initial mit `undefined`
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers

Ruft man die `getValue` Methode von `KolSelect` (mit einer vorausgewählten Option) initial auf, so erhält man ein Promise, das mit `undefined` statt dem gewählten Wert resolved.
Erst nach dem Ändern der gewählten Option erhält man einen korrekten Wert.

## Reproduktion

Schritte zum Reproduzieren des Verhaltens:
- Gehe zu https://develop--kolibri-public-ui.netlify.app/#/scenarios/inputs-get-value
- Klicke in der Zeile `KolSelect` auf `getValue()`

### PR DESCRIPTION
**Pull request by anicyne**
Refs: #6440

### CODE REVIEW

File: packages/components/src/components/select/shadow.tsx [hunk 1]
```diff
@@ -56,7 +56,7 @@ export class KolSelect implements SelectAPI {
 	@Method()
 	// eslint-disable-next-line @typescript-eslint/require-await
 	public async getValue(): Promise<Stringified<W3CInputValue[]> | undefined> {
-		return this._value;
+		return this.state._value;
```
Comment (deleonio) [inline packages/components/src/components/select/shadow.tsx:59]: 👍

**Review by deleonio — APPROVED** [review]
