### PR TITLE
Fix handling of minus sign in number input

### LINKED ISSUE #7072: 🐞 Bug: KolInputNumber verschluckt Minus wenn _value gesetzt ist
### Link to the code that reproduces this issue:
https://stackblitz.com/edit/vitejs-vite-rws84l?file=src%2FApp.tsx

### How to reproduce issue?
1. Gebe ins erste Feld ein Minus ein
 - es wird nicht angezeigt
 2. Gebe im ersten Feld ein weiteres Minus ein
 - nun wird es angezeigt 
 3. Im zweiten Feld, wird das Minus sofort bei der ersten Eingabe angezeigt

### Current vs. Expected:
Sobald `_value` mitgegeben wird, wird das initiale Minus verschluckt und erst beim erneuten Tippen angezeigt. Dies ist insofern problematisch, wenn ein Nutzer z.B. per Tastatur einen negativen Wert eingeben will, z.B. `-1`, dann wird am Ende nur `1` angezeigt, da das Minus verschluckt wurde. Das Minus sollte sofort angezeigt werden, auch wenn `_value` mitgegeben wird.

### Environment informations:
```bash {
 "Operating System": {
 "platform": "darwin",
 "arch": "arm64",
 "version": "23.6.0"
 },
 "Binaries": {
 "node": "v20.17.0",
 "npm": "10.8.2",
 "pnpm": "8.12.1",
 "yarn": "N/A"
 },
 "Relevant Packages": {
 "@public-ui/components": "2.1.8",
 "@public-ui/react": "2.1.8",
 "react": "^18.3.1",
 "react-dom": "^18.3.1",
 "typescript": "5.5.4"
 }
 } ```

### PR DESCRIPTION
**Pull request by anicyne**
Refs: #7072

The A11y and PO reviews will only take place after all other DoD steps have been completed by the Developer:
- [x] Meaningful pull request title for the release notes
- [x] Pull request is linked to an issue and all changes relate to the issue
- [x] Tests to protect this code implemented (if applicable)
- [x] Manual test performed successfully (if applicable)
- [x] Documentation or migration has been updated (if applicable)

### CODE REVIEW

File: packages/components/src/components/input-number/shadow.tsx [hunk 1]
```diff
@@ -472,11 +472,7 @@ export class KolInputNumber implements InputNumberAPI, FocusableElement {
 
 	@Watch('_value')
 	public validateValue(value?: number | Iso8601 | null): void {
-		this.controller.validateValueEx(value, (v) => {
-			if (v === '' && this.inputRef) {
-				this.inputRef.value = '';
-			}
-		});
```
Comment (laske185) [inline packages/components/src/components/input-number/shadow.tsx:479]: Damit wurde commit 9b7d9d8ad894c89f401006832176e82eb2402892 für Ticket #2257 rückgängig gemacht.

Comment (laske185) [reply packages/components/src/components/input-number/shadow.tsx:479]: Da das `input-date` aber nicht mehr das `input-number` benutzt, scheint es i.O. zu sein.

**Review by laske185 — APPROVED** [review]
