### PR TITLE
Submit form on enter for select and radio; Fix radio form association

### LINKED ISSUE #6135: 🐞 Bug: Verschiedene Eingabefelder können nicht mit Enter abgeschickt werden
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

Die Eingabefelder-Komponenten haben überwiegend ein Feature umgesetzt, das dafür sorgt, dass beim Drücken von `Enter` das umgebende Formular abgesendet wird.

Folgende Komponenten unterstützen dies noch nicht:
* select
* input-color
* input-file
* input-radio

Für die Komponenten sollte jeweils geprüft werden, wie das native Verhalten der Browser aussieht, wenn das jeweilige Eingabefeld fokussiert ist und Enter gedrückt wird.
Wichtig ist auch, dass das Formular nicht ungewollt, z.B. der Auswahl einer Select-Option, abgeschickt wird.

--- 

Zusätzlich in diesem Ticket:

Form associated elements werden für Radio-Elemente nicht korrekt gesetzt. Das Attribut `checked` fehlt.

### PR DESCRIPTION
**Pull request by sdvg**
### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title for the release notes
- [x] Pull request is linked to a problem
- [x] All changes relate to the problem
- [x] A11y tests performed successfully or not relevant
- [x] Manual test performed successfully (by reviewer) or not relevant

### CODE REVIEW

**Review by laske185 — APPROVED** [review]

File: packages/components/src/components/select/component.tsx [hunk 1]
```diff
@@ -449,4 +451,13 @@ export class KolSelect implements SelectAPI {
 			this.state._on.onChange(event, this._value);
 		}
 	}
+
+	private readonly onKeyDown = (event: KeyboardEvent) => {
+		if (event.code === 'Enter' || event.code === 'NumpadEnter') {
```
Comment (laske185) [inline packages/components/src/components/select/component.tsx]: Das kollidiert aber jetzt mit dem Aufklappen des Selects.

**Review by laske185 — CHANGES_REQUESTED** [review]

**Review by laske185 — DISMISSED** [review]

File: packages/components/src/components/select/component.tsx (hunk 1 above)
Comment (laske185) [reply packages/components/src/components/select/component.tsx]: Durch das Umschließen in eine Form wird das Problem umgangen.

**Review by laske185 — APPROVED** [review]
