### PR TITLE
fix: experimental mode for static form handling

### LINKED ISSUE #6063: 🐞 Bug: `experimental-mode` funktioniert ab Version 2 nicht mehr
Wir müssen mal schauen, ob der Status richtig gesetzt wird und von den Komponenten korrekt behandelt wird.

Die Dev-Tools geben `Experimental mode activated` aus.

Reproduktionsbeispiel: https://stackblitz.com/edit/vitejs-vite-gmrxib (nicht ganz vollständig)

### PR DESCRIPTION
**Pull request by deleonio**
### :ballot_box_with_check: Definition of Done checklist
- [ ] Meaningful title and valuable description in pull request
- [ ] Pull request linked to one or more issues
  - [ ] Acceptance criteria of the linked issue satisfied
  - [ ] All changes relates to the issue
- [ ] All tests passed
  - [ ] Code changes tested manually if not covered by automated tests
  - [x] A11y tests successful carried out

### CODE REVIEW

File: packages/samples/react/src/scenarios/static-form.tsx [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+		<>
+			<SampleDescription>
+				<p>This sample shows how you can use KoliBri in static form context, too.</p>
+				<ol>
+					<li>
+						First you have to enable the <code>experimental mode</code>:{' '}
+						<code className="bg-gray-200">&lt;meta name=&quot;kolibri&quot; content=&quot;dev-mode=false;experimental-mode=true;&quot; /&gt;</code>
+					</li>
+					<li>
+						Actually you have to use a native <code>form</code> element:{' '}
```
Comment (sdvg) [inline packages/samples/react/src/scenarios/static-form.tsx]:
```suggestion
						Currently you have to use a native <code>form</code> element:{' '}
```

File: packages/samples/react/src/scenarios/static-form.tsx [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+						<code className="bg-gray-200">&lt;form method=&quot;GET&quot;&gt;...&lt;/form&gt;</code>
+					</li>
+					<li>
+						It is important in static usage to give every input a <code>name</code> attribute, because the form data will be sent as a query string:{' '}
```
Comment (sdvg) [inline packages/samples/react/src/scenarios/static-form.tsx]: Den Teilsatz würde ich vielleicht weglassen: `, because the form data will be sent as a query string:`

Das Formular kann ja auch als FormData verschickt werden, das würde ich aber nicht alles beschrieben.

**Review by sdvg — APPROVED** [review]
