### PR TITLE
Fix select-aria in combobox and single-select

### LINKED ISSUE #7059: Bug: aria-selected in Combobox und Single-select ist unvollständig gesetzt
Das aria-selected Attribut sollte für das ausgewählte Item als  `aria-selected="true"` angezeigt werden. Aktuell wird das Attribut ohne Wert angezeigt und erscheint nur als `aria-selected`.

### PR DESCRIPTION
**Pull request by anicyne**
Refs: #7059

The A11y and PO reviews will only take place after all other DoD steps have been completed by the Developer:
- [x] Meaningful pull request title for the release notes
- [x] Pull request is linked to an issue and all changes relate to the issue
- [x] Tests to protect this code implemented (if applicable)
- [x] Manual test performed successfully (if applicable)
- [x] Documentation or migration has been updated (if applicable)

### CODE REVIEW

File: packages/components/src/components/combobox/shadow.tsx [hunk 1]
```diff
@@ -245,7 +245,7 @@ export class KolCombobox implements ComboboxAPI {
 												data-index={index}
 												tabIndex={-1}
 												role="option"
-												aria-selected={this.state._value === option}
+												aria-selected={this.state._value === option ? 'true' : 'false'}
```
Comment (sdvg) [inline packages/components/src/components/combobox/shadow.tsx]:
```suggestion
												aria-selected={this.state._value === option ? 'true' : undefined}
```

Ich bin mir nicht sicher, ob es in der Praxis mit `"false"` ein Problem gibt, aber der Default-Value hier sollte `undefined` sein.

So sind auch die WCAG-Beispiele umgesetzt: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/
Siehe auch: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-selected#values

File: packages/components/src/components/single-select/shadow.tsx [hunk 2]
```diff
@@ -277,7 +277,7 @@ export class KolSingleSelect implements SingleSelectAPI {
 												}}
 												tabIndex={-1}
 												role="option"
-												aria-selected={this.state._value === (option as Option<string>).value}
+												aria-selected={this.state._value === (option as Option<string>).value ? 'true' : 'false'}
```
Comment (sdvg) [inline packages/components/src/components/single-select/shadow.tsx]:
```suggestion
												aria-selected={this.state._value === (option as Option<string>).value ? 'true' : undefined}
```

**Review by sdvg — CHANGES_REQUESTED** [review]

**Review by sdvg — APPROVED** [review]
