### PR TITLE
fix: backspace behavior at input date

### LINKED ISSUE #5800: 💡 Bug: Backspace-Verhalten von InputDate
in den KoliBri-Versionen bis einschließlich 1.7.7 ein unerwartetes Verhalten von KolInputDate bei Bedienung mit der Tastatur aufgefallen.

Vorgehen:
1. Zahlen in KolInputDate eingeben.
2. Backspace betätigen.

Erwartetes Verhalten:
Bei Betätigung von Backspace wird das jeweils zuletzt eingegebene Zeichen gelöscht.

Tatsächliches Verhalten:
Bei Betätigung von Backspace wird das Eingabefeld komplett geleert.

```html
<kol-input-date></kol-input-date>
<input type="date">
```

Beobachtung: Bei KoliBri wird der Wert ohne Jahr insgesamt invalide und wird deshalb komplett zurückgesetzt. Bei nativen Input können die einzelnen Segmente des Datums einzeln gelöscht und bearbeitet werden.

### PR DESCRIPTION
**Pull request by laske185**
Change the value of input-date on blur instead of at the onChange-event.

Allows to remove single blocks of the date or time without deleting the complete input.

Closes: #5800

### CODE REVIEW

File: packages/components/src/components/input-date/controller.ts [hunk 1]
```diff
@@ -116,8 +116,8 @@ export class InputDateController extends InputIconController implements Watches
 		);
 	};
 
-	protected onChange(event: Event): void {
-		super.onChange(event);
+	protected onBlur(event: Event): void {
```
Comment (deleonio) [inline packages/components/src/components/input-date/controller.ts:119]: Ist das echt alles?!

**Review by deleonio — CHANGES_REQUESTED** [review]

**Review by deleonio — APPROVED** [review]
