### PR TITLE
refact: initialize i18n Service before first translation if not happened

### LINKED ISSUE #6391: Selbstständige Initialisierung des I18nServices
Es wurde gemeldet, dass seit der Version 2.0.9 eine interne Exception in i18n ausgelöst wird:

„In @public-ui/components/dist/kolibri (2.0.8) gibt es die Datei "i18n-8b7a6ddc.js", welche keinen Fehler verursacht.
Ab der Version 2.0.9 wurde diese geändert und aufgeteilt(?) zu "i18n-7a7ff96e.js" und "i18n-0c047df5.js"

index-59e9528b.js:4 Error: i18n not initialized yet
    at getI18nInstance (i18n-0c047df5.js:4:752)
    at translate (i18n-7a7ff96e.js:4:2936)

Diese Exception kommt bei praktisch allen KoliBri-Elementen, welche eigenen Text beinhalten ab 2.0.9ff.“

Ursache für das Verhalten ist, dass der I18nService vor der Nutzung durch eine Komponente initialisiert werden soll. Da die Texte statisch vorhanden sind, kann beim ersten Aufruf der Service sich auch initialisiert werden, wenn bisher nicht durch die registry-Funktion geschehen. Damit kommt es nicht mehr zur Exception.

### PR DESCRIPTION
**Pull request by laske185**
Closes: #6391

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title for the release notes
- [x] Pull request is linked to a problem
- [x] All changes relate to the problem
- [x] A11y tests performed successfully or not relevant
- [ ] Manual test performed successfully (by reviewer) or not relevant

### CODE REVIEW

File: packages/components/src/core/i18n.ts [hunk 1]
```diff
@@ -91,19 +104,17 @@ export class I18nService {
...
-	translations?:
+	translations:
 		| Generic.I18n.RegisterPatch<Generic.I18n.Locale.ISO_639_1, string, string>
 		| Generic.I18n.RegisterPatch<Generic.I18n.Locale.ISO_639_1, string, string>[]
-		| Set<Generic.I18n.RegisterPatch<Generic.I18n.Locale.ISO_639_1, string, string>>,
+		| Set<Generic.I18n.RegisterPatch<Generic.I18n.Locale.ISO_639_1, string, string>> = TRANSLATIONS,
 ) => {
 	i18n = new I18nService(lng);
 	i18n.addTranslations(translations);
+	return i18n;
```
Comment (deleonio) [inline packages/components/src/core/i18n.ts:119]: Wieso?!

**Review by deleonio — CHANGES_REQUESTED** [review]

**Review by deleonio — APPROVED** [review]
