### PR TITLE
fix: value handling for inputs

### LINKED ISSUE #6067: 🛠️ Todo: Static File Input Handling mit type=file umsetzen
Im static Mode werden die im Shadow Root versteckten Feld-Werte nach außen synchronisiert. Für `file` müsste ein separates Handling umgesetzt werden. Die ausgewählten File-Objekte müssten an das äußere File-Feld sychronisiert werden.

### PR DESCRIPTION
**Pull request by deleonio**
### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title for the release notes
- [x] Pull request is linked to an issue
- [x] All changes relate to the issue
- [ ] A11y tests performed successfully
- [x] Code review carried out successfully
- [ ] Manual test performed successfully

### CODE REVIEW

File: packages/components/src/components/input-adapter-leanup/associated.controller.ts [hunk 1]
```diff
@@ -27,13 +44,12 @@ export class AssociatedInputController implements Watches {
...
 		this.type = type;
 
-		if (getExperimentalMode() && isAssociatedTagName(this.host?.tagName)) {
+		if (this.experimentalMode && isAssociatedTagName(this.host?.tagName)) {
 			this.host?.querySelectorAll('input,select,textarea').forEach((el) => {
 				this.host?.removeChild(el);
 			});
 			switch (this.type) {
 				case 'button':
-				case 'checkbox':
```
Comment (deleonio) [inline packages/components/src/components/input-adapter-leanup/associated.controller.ts:36]: Checkbox folgt dem `default`, weil so das Setzen des Wertes einfacher mit einem `hidden`-Field ist. Ohne `checked` setzen zu müssen.

**Review by laske185 — APPROVED** [review]
